# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/jsonschema/schema.json
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: template-martin-alpine-dotnet-runtime-web
  namespace: argo-workflows
spec:
  templates:
    - name: build
      inputs:
        parameters:
          - { name: branch,  default: master }
          - { name: version, default: latest }
      volumes:
        - name: kaniko-config
          secret:
            secretName: martin-auth-ghcr
      container:
        image: gcr.io/kaniko-project/executor:v1.11.0
        args:
          - --destination=ghcr.io/martin-deploy/martin-alpine-dotnet-runtime-web:{{inputs.parameters.version}}
          - --context=git://github.com/martin-deploy/dockerfiles.git#refs/heads/{{inputs.parameters.branch}}
          - --dockerfile=Dockerfile.martin-alpine-dotnet-runtime-web
          - --single-snapshot
          # - --build-arg key=value                  This flag allows you to pass in ARG values at build time. Set it repeatedly for multiple values.
          - --label=org.opencontainers.image.source=https://github.com/martin-deploy/dockerfiles
          - --label=org.opencontainers.image.created={{workflow.creationTimestamp.RFC3339}}
        volumeMounts:
          - mountPath: /kaniko/.docker/config.json
            name: kaniko-config
            subPath: .dockerconfigjson
