# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/jsonschema/schema.json
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: template-martin-alpine
  namespace: argo-workflows
spec:
  templates:
    - name: build
      inputs:
        parameters:
          - { name: branch,  default: master }
          - { name: version, default: latest }
      container:
        image: gcr.io/kaniko-project/executor:v1.11.0
        args:
          - --destination=ghcr.io/martin-deploy/martin-alpine:{{inputs.parameters.version}}
          - --context=git://https://github.com/martin-deploy/dockerfiles.git#refs/heads/{{inputs.parameters.branch}}
          # - --git branch={{inputs.parameters.branch}},single-branch=true,recurse-submodules=false
          - --dockerfile=Dockerfile.martin-alpine
          - --single-snapshot
          # - --build-arg multi-arg type                  This flag allows you to pass in ARG values at build time. Set it repeatedly for multiple values.
          # - --label multi-arg type                      Set metadata for an image. Set it repeatedly for multiple labels.
          # - --insecure                                  Push to insecure registry using plain HTTP
          # - --insecure-registry multi-arg type          Insecure registry using plain HTTP to push and pull. Set it repeatedly for multiple registries.
          # - --skip-tls-verify                           Push to insecure registry ignoring TLS verify
          # - --skip-tls-verify-registry multi-arg type   Insecure registry ignoring TLS verify to push and pull. Set it repeatedly for multiple registries.
